// Owner revenue report → PDF, via headless Chromium (Playwright — already a
// server dep for the CRM mockups + stemfra_business export). We build a
// self-contained, print-styled HTML statement and let Chrome lay it out, so the
// PDF has real selectable text + clean page breaks (no html2canvas fuzz).
const { chromium } = require('playwright');

function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}
const money = (c) => '$' + ((c || 0) / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function reportHtml(m) {
  const rows = m.transactions.map((t) => `<tr>
      <td>${esc(t.date)}</td>
      <td>${esc(t.service)}</td>
      <td>${esc(t.howPaid)}</td>
      <td style="text-transform:capitalize">${esc(t.status)}</td>
      <td class="amt"${t.kind === 'refunded' ? ' style="color:#b91c1c"' : ''}>${t.kind === 'refunded' ? '-' : ''}${money(t.cents)}</td>
    </tr>`).join('');
  const setAside = money(Math.round((m.totalCents || 0) * 0.27));
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page { size: A4; margin: 1.6cm; }
    * { box-sizing: border-box; }
    body { font-family: -apple-system, 'Segoe UI', Arial, sans-serif; color: #1a1a1a; font-size: 12px; margin: 0; }
    h1 { font-size: 20px; margin: 0; }
    .sub { color: #777; font-size: 12px; margin-top: 3px; }
    .cards { display: flex; gap: 10px; margin: 18px 0 4px; }
    .card { flex: 1; border: 1px solid #e6e6e6; border-radius: 8px; padding: 10px 12px; }
    .card .l { font-size: 9px; text-transform: uppercase; letter-spacing: .05em; color: #999; }
    .card .v { font-size: 17px; font-weight: 600; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 18px; }
    th { text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: .04em; color: #999; border-bottom: 2px solid #e6e6e6; padding: 6px 8px; }
    td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; }
    .amt { text-align: right; white-space: nowrap; }
    tfoot td { font-weight: 700; border-top: 2px solid #ccc; border-bottom: none; }
    .note { margin-top: 20px; border: 1px solid #e6e6e6; background: #fafafa; border-radius: 8px; padding: 12px; }
    .disc { color: #999; font-size: 10px; margin-top: 6px; }
    .foot { margin-top: 20px; color: #aaa; font-size: 9px; }
  </style></head><body>
    <h1>${esc(m.businessName)}</h1>
    <div class="sub">Revenue report &nbsp;·&nbsp; ${esc(m.fromLabel)} – ${esc(m.toLabel)}</div>
    <div class="cards">
      <div class="card"><div class="l">Total revenue</div><div class="v">${money(m.totalCents)}</div></div>
      <div class="card"><div class="l">Paid online</div><div class="v">${money(m.onlineCents)}</div></div>
      <div class="card"><div class="l">Collected at visit</div><div class="v">${money(m.atVisitCents)}</div></div>
      <div class="card"><div class="l">Customers</div><div class="v">${m.customers.total}</div></div>
    </div>
    ${m.membershipMrrCents > 0 ? `<div class="sub">Recurring memberships: <strong>${money(m.membershipMrrCents)}/mo</strong> from ${m.membershipCount} active member${m.membershipCount === 1 ? '' : 's'} (monthly run-rate, separate from the one-time revenue above).</div>` : ''}
    ${m.atVisitDueCents > 0 ? `<div class="sub">Of the at-visit total, <strong>${money(m.atVisitDueCents)}</strong> is still marked as due (not yet collected).</div>` : ''}
    ${m.refundedCents > 0 ? `<div class="sub">Refunded in this period: <span style="color:#b91c1c">-${money(m.refundedCents)}</span> (not included in totals).</div>` : ''}
    <table>
      <thead><tr><th>Date</th><th>Service</th><th>How paid</th><th>Status</th><th class="amt">Amount</th></tr></thead>
      <tbody>${rows || '<tr><td colspan="5" style="color:#999">No revenue in this period.</td></tr>'}</tbody>
      <tfoot><tr><td colspan="4">Total collected + due</td><td class="amt">${money(m.totalCents)}</td></tr></tfoot>
    </table>
    <div class="note">
      <strong>Putting money aside for taxes</strong>
      <div style="margin-top:4px">Many self-employed owners set aside roughly 25–30% of their income for taxes — on ${money(m.totalCents)} that's about ${setAside} to keep on hand. Your online card payments are also in your own Stripe dashboard; this report adds what you collected at the visit.</div>
      <div class="disc">This is a general guide, not tax advice — your actual taxes depend on your situation and location. Check with a tax professional.</div>
    </div>
    <div class="foot">Generated by Stemfra${m.generatedAt ? ' · ' + esc(m.generatedAt) : ''}</div>
  </body></html>`;
}

async function renderReportPdf(model) {
  let browser;
  try {
    browser = await chromium.launch({ args: ['--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1000, height: 1400 } });
    page.setDefaultTimeout(60_000);
    await page.setContent(reportHtml(model), { waitUntil: 'networkidle', timeout: 60_000 });
    await page.evaluate(() => (document.fonts ? document.fonts.ready : true));
    return await page.pdf({ printBackground: true, format: 'A4', preferCSSPageSize: true, timeout: 60_000 });
  } finally {
    if (browser) { try { await browser.close(); } catch { /* ignore */ } }
  }
}

module.exports = { renderReportPdf, reportHtml };
